[package]
name = "libharu"
version = "0.0.101"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libharu-sys = "*"
anyhow = "*"
bitflags = "*"
encoding_rs = "*"
